# Chapter 6. Getting Data In and Out

*Data Analytics with Python and Jupyter Notebook*

Companion notebook. Run each cell in order with **Shift + Enter**, and read the chapter alongside it.

## 6.1 Data comes in many shapes

Start the notebook with the usual imports:

In [1]:
import json
import sqlite3

import numpy as np
import pandas as pd

In [2]:
# Keep printed tables narrow enough for the book's pages
pd.set_option("display.width", 80)

## 6.2 Reading CSV files properly

### Look before you load

Because a CSV is plain text, you can peek at its first few lines before handing it to pandas. This habit saves a lot of confusion. Python's built-in `open()` reads a file, and a `with` block makes sure it is closed afterwards:

In [3]:
with open("../data/bean_there_sales.csv") as f:
    for _ in range(3):
        print(f.readline(), end="")

date,store,product,category,quantity,unit_price,revenue
2026-01-01,Downtown,Espresso,Coffee,30,3.0,90.0
2026-01-01,Downtown,Latte,Coffee,53,4.5,238.5

### The options you will use most

Here are several at once. We load only three columns, turn `date` into real dates, make it the index, and stop after six rows:

In [4]:
pd.read_csv(
    "../data/bean_there_sales.csv",
    usecols=["date", "store", "revenue"],
    parse_dates=["date"],
    index_col="date",
    nrows=6,
)

               store  revenue
date
2026-01-01  Downtown    90.00
2026-01-01  Downtown   238.50
2026-01-01  Downtown   148.75
2026-01-01  Downtown    66.50
2026-01-01  Downtown    84.50
2026-01-01  Downtown    67.85

### Missing values

## 6.3 When a CSV is not quite a CSV

Bean There has started buying specialty products from three European suppliers, and their invoicing system exports a file called `ch06_supplier_invoices.csv`. Let's load it the usual way:

In [5]:
try:
    invoices = pd.read_csv("../data/ch06_supplier_invoices.csv")
except UnicodeDecodeError as err:
    print("UnicodeDecodeError:", err)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 80: invalid start byte

### What is an encoding?

The error says byte `0xf6` cannot be decoded as UTF-8. In Windows-1252, `0xf6` is the letter ö. So the file is almost certainly in Windows-1252. Let's look at the raw text, telling Python which encoding to use this time:

In [6]:
path = "../data/ch06_supplier_invoices.csv"
with open(path, encoding="cp1252") as f:
    for _ in range(3):
        print(f.readline(), end="")

Rechnung Nr.;Datum;Lieferant;Artikel;Menge;Preis;Gesamt
4101;05.01.2026;Kaffeerösterei Müller;Espresso beans 1 kg;5;18,40;92,00
4102;05.01.2026;Tostadores Peña;Cold brew concentrate 5 l;10;32,90;329,00

### Telling pandas about the file

Each surprise has a matching option:

In [7]:
invoices = pd.read_csv(
    path,
    encoding="cp1252",
    sep=";",
    decimal=",",
)
invoices.head(3)

,Rechnung Nr.,Datum,Lieferant,Artikel,Menge,Preis,Gesamt
0,4101,05.01.2026,Kaffeerösterei Müller,Espresso beans 1 kg,5,18.40,92.00
1,4102,05.01.2026,Tostadores Peña,Cold brew concentrate 5 l,10,32.90,329.00
2,4103,19.01.2026,Pâtisserie Hélène,Croissants (box of 24),3,21.75,65.25

pandas wrapped the wide table, as you saw in Chapter 5, but the text is readable and `Preis` and `Gesamt` are real numbers. The dates are still text, and their format, day then month then year separated by dots, is not one pandas should guess at. `pd.to_datetime()` converts a column to dates, and `format=` spells out the pattern exactly: `%d` is the day, `%m` the month and `%Y` the four-digit year. Let's convert the dates and give the columns English names at the same time:

In [8]:
invoices = invoices.rename(columns={
    "Rechnung Nr.": "invoice", "Datum": "date", "Lieferant": "supplier",
    "Artikel": "item", "Menge": "qty", "Preis": "price", "Gesamt": "total",
})
invoices["date"] = pd.to_datetime(invoices["date"], format="%d.%m.%Y")
invoices.dtypes

invoice              int64
date        datetime64[us]
supplier               str
item                   str
qty                  int64
price              float64
total              float64
dtype: object

Every column now has the right type, so we can trust calculations on it:

In [9]:
invoices.groupby("supplier")["total"].sum()

supplier
Kaffeerösterei Müller     552.00
Pâtisserie Hélène         543.75
Tostadores Peña          1118.60
Name: total, dtype: float64

## 6.4 Reading Excel workbooks

Bean There's finance team has sent `ch06_store_targets.xlsx`, a workbook with monthly revenue targets. A workbook can hold several **sheets** (tabs). Before loading anything, list them with `pd.ExcelFile()`:

In [10]:
workbook = pd.ExcelFile("../data/ch06_store_targets.xlsx")
workbook.sheet_names

['Targets', 'Stores', 'Notes']

### The first sheet, and the title-row problem

By default `read_excel()` loads the **first** sheet:

In [11]:
pd.read_excel("../data/ch06_store_targets.xlsx").head()

   Bean There monthly revenue targets Unnamed: 1      Unnamed: 2
0  Prepared by Finance, December 2025        NaN             NaN
1                                 NaN        NaN             NaN
2                               store      month  revenue_target
3                            Downtown    2026-01           22000
4                            Downtown    2026-02           21000

Opening the file in Excel shows that the real column names are on row 4. Skip the three rows above them with `skiprows=3`:

In [12]:
targets = pd.read_excel(
    "../data/ch06_store_targets.xlsx",
    sheet_name="Targets",
    skiprows=3,
)
targets

        store    month  revenue_target
0    Downtown  2026-01           22000
1    Downtown  2026-02           21000
2    Downtown  2026-03           24000
3  University  2026-01           16500
4  University  2026-02           15500
5  University  2026-03           18500
6   Riverside  2026-01           13000
7   Riverside  2026-02           12500
8   Riverside  2026-03           14500

### Other sheets, and all sheets at once

`sheet_name` accepts a sheet's name or its position (0 is the first). The `Stores` sheet is a simple table:

In [13]:
pd.read_excel("../data/ch06_store_targets.xlsx", sheet_name="Stores")

        store       neighborhood  seats     opened       manager
0    Downtown  Business district     40 2019-03-01    Priya Nair
1  University             Campus     55 2021-08-16    Tom Okafor
2   Riverside          Riverside     24 2022-05-06  Lena Fischer

Pass `sheet_name=None` to load **every** sheet. You get back a dictionary (Chapter 3) whose keys are the sheet names and whose values are DataFrames:

In [14]:
sheets = pd.read_excel("../data/ch06_store_targets.xlsx",
                       sheet_name=None)
for name, df in sheets.items():
    print(f"{name}: {df.shape[0]} rows x {df.shape[1]} columns")

Targets: 12 rows x 3 columns
Stores: 3 rows x 5 columns
Notes: 2 rows x 1 columns

The Targets sheet shows 12 rows because, without `skiprows`, the title rows count too.

In [15]:
sheets["Notes"]

                                                note
0   Targets are in US dollars and exclude sales tax.
1  Riverside target reduced in February for roadw...

## 6.5 Reading JSON

### Flat JSON: one record per item

The simplest JSON is a list of records that all have the same keys, like the Bean There menu. Here are its first lines:

In [16]:
with open("../data/ch06_menu.json") as f:
    print(f.read()[:200])

[
  {
    "product": "Espresso",
    "category": "Coffee",
    "price": 3.0,
    "vegan": true,
    "launched": "2019-03-01"
  },
  {
    "product": "Latte",
    "category": "Coffee",
    "price": 4.5

When JSON looks like this, `pd.read_json()` turns it into a DataFrame in one step, with one row per record:

In [17]:
menu = pd.read_json("../data/ch06_menu.json")
menu

            product category  price  vegan    launched
0          Espresso   Coffee   3.00   True  2019-03-01
1             Latte   Coffee   4.50  False  2019-03-01
2        Cappuccino   Coffee   4.25  False  2019-03-01
3         Cold Brew   Coffee   4.75   True  2023-06-01
4         Croissant   Bakery   3.25  False  2019-03-01
5  Blueberry Muffin   Bakery   2.95  False  2021-09-15

### Nested JSON

Real JSON is often **nested**: a value can itself be a dictionary or a list. The loyalty app's export is a good example. Let's load it with Python's `json` module, which turns JSON into ordinary dictionaries and lists, and look at the first member:

In [18]:
with open("../data/ch06_loyalty_members.json") as f:
    loyalty = json.load(f)

print(loyalty.keys())
loyalty["members"][0]

dict_keys(['exported', 'members'])

{'member_id': 50101,
 'name': 'Ana Park',
 'joined': '2024-06-02',
 'home_store': 'Downtown',
 'favorites': {'drink': 'Latte', 'milk': 'Oat'},
 'visits': [{'date': '2026-03-14', 'store': 'Downtown', 'spend': 4.0},
  {'date': '2026-03-23', 'store': 'Downtown', 'spend': 6.75},
  {'date': '2026-03-31', 'store': 'Downtown', 'spend': 5.0}]}

`pd.json_normalize()` does exactly that. It turns each record into a row and spreads nested dictionaries into columns, joining the names with a dot:

In [19]:
members = pd.json_normalize(loyalty["members"])
members[["member_id", "name", "favorites.drink", "favorites.milk"]]

   member_id          name favorites.drink favorites.milk
0      50101      Ana Park           Latte            Oat
1      50102      Ben Lowe       Cold Brew            NaN
2      50103  Chloe Moreau      Cappuccino          Whole
3      50104      Dev Shah        Espresso            NaN
4      50105    Esme Quinn           Latte         Almond
5      50106  Femi Adeyemi           Latte          Whole

### One row per visit

To analyze visits, we want one row per **visit**, with the member's details repeated alongside. `json_normalize` does this with `record_path`, which names the list to unpack, and `meta`, which lists the member fields to carry along:

In [20]:
visits = pd.json_normalize(
    loyalty["members"],
    record_path="visits",
    meta=["member_id", "name", "home_store"],
)
visits

          date       store  spend member_id          name  home_store
0   2026-03-14    Downtown   4.00     50101      Ana Park    Downtown
1   2026-03-23    Downtown   6.75     50101      Ana Park    Downtown
2   2026-03-31    Downtown   5.00     50101      Ana Park    Downtown
3   2026-03-14  University   8.75     50102      Ben Lowe  University
4   2026-03-17  University  13.50     50102      Ben Lowe  University
5   2026-03-26  University   3.75     50102      Ben Lowe  University
6   2026-03-20    Downtown  13.50     50103  Chloe Moreau   Riverside
7   2026-03-22   Riverside   6.00     50103  Chloe Moreau   Riverside
8   2026-03-04    Downtown   3.50     50104      Dev Shah    Downtown
9   2026-03-05    Downtown  13.25     50104      Dev Shah    Downtown
10  2026-03-09    Downtown  11.50     50104      Dev Shah    Downtown
11  2026-03-04    Downtown   5.00     50105    Esme Quinn  University
12  2026-03-20  University   5.50     50105    Esme Quinn  University
13  2026-03-27  University   9.25     50105    Esme Quinn  University
14  2026-03-20   Riverside  13.50     50106  Femi Adeyemi   Riverside
15  2026-03-29   Riverside   3.25     50106  Femi Adeyemi   Riverside

Now each row is one visit, ready for the techniques in Chapter 5. For example, the total each member spent in March:

In [21]:
(
    visits
    .groupby("name")["spend"]
    .sum()
    .sort_values(ascending=False)
)

name
Dev Shah        28.25
Ben Lowe        26.00
Esme Quinn      19.75
Chloe Moreau    19.50
Femi Adeyemi    16.75
Ana Park        15.75
Name: spend, dtype: float64

## 6.6 Reading from SQL databases

### Connecting to SQLite

We will use **SQLite**, a database that lives in a single file and comes built into Python through the `sqlite3` module. Bean There's till data has been loaded into `ch06_bean_there.db`. Connecting takes one line:

In [22]:
con = sqlite3.connect("../data/ch06_bean_there.db")

`con` is a **connection**, an open line to the database. Every database keeps a list of its tables; in SQLite it lives in a special table called `sqlite_master`. Let's ask it what tables exist, using `pd.read_sql_query()`, which takes a SQL query and a connection:

In [23]:
pd.read_sql_query(
    "SELECT name FROM sqlite_master WHERE type = 'table'", con
)

       name
0     sales
1    stores
2  products

### A first query

The basic shape of a SQL query is `SELECT columns FROM table`, optionally followed by `WHERE` (filter rows), `ORDER BY` (sort) and `LIMIT` (keep the first n rows). Writing SQL keywords in capitals is a convention that makes them easy to spot. Long queries are easier to read in a triple-quoted string, which can span several lines:

In [24]:
query = """
SELECT date, store, product, quantity, revenue
FROM sales
WHERE product = 'Cold Brew' AND store = 'Downtown'
ORDER BY revenue DESC
LIMIT 5
"""
pd.read_sql_query(query, con)

         date     store    product  quantity  revenue
0  2026-03-25  Downtown  Cold Brew        50   237.50
1  2026-03-14  Downtown  Cold Brew        46   218.50
2  2026-03-28  Downtown  Cold Brew        45   213.75
3  2026-03-20  Downtown  Cold Brew        41   194.75
4  2026-03-17  Downtown  Cold Brew        40   190.00

### Letting the database do the work

Databases are very good at summarizing. With `GROUP BY` and `SUM()`, the database adds up revenue per store and sends back just three rows instead of 1,620:

In [25]:
query = """
SELECT store, SUM(revenue) AS revenue, SUM(quantity) AS units
FROM sales
GROUP BY store
ORDER BY revenue DESC
"""
pd.read_sql_query(query, con)

        store  revenue  units
0    Downtown  70205.3  18013
1  University  50570.4  12979
2   Riverside  40138.2  10335

SQL can also combine tables with `JOIN`. Here we attach each store's manager from the `stores` table:

In [26]:
query = """
SELECT s.store, st.manager, SUM(s.revenue) AS revenue
FROM sales AS s
JOIN stores AS st ON s.store = st.store
GROUP BY s.store, st.manager
"""
pd.read_sql_query(query, con)

        store       manager  revenue
0    Downtown    Priya Nair  70205.3
1   Riverside  Lena Fischer  40138.2
2  University    Tom Okafor  50570.4

### Parameters and dates

When part of a query comes from a variable, such as a product the user picked, do not paste it into the string yourself. Put a `?` placeholder in the query and pass the values in `params`. The database then handles quoting safely:

In [27]:
query = """
SELECT date, store, quantity
FROM sales
WHERE product = ? AND date >= ?
"""
latte_march = pd.read_sql_query(
    query, con, params=("Latte", "2026-03-01"), parse_dates=["date"]
)
print(latte_march.shape)
print(latte_march.dtypes)

(93, 3)
date        datetime64[us]
store                  str
quantity             int64
dtype: object

When you have finished with a database, close the connection:

In [28]:
con.close()

### Other databases

SQLite is perfect for learning and for small projects. Companies more often run PostgreSQL, MySQL, SQL Server or a cloud warehouse such as BigQuery or Snowflake. pandas talks to these through a library called **SQLAlchemy** plus a driver for the specific database. The pandas side stays the same; only the connection changes. Here is what it looks like for PostgreSQL. This is an example to try on your own machine once you have a database to connect to; the address, user and password are placeholders:

*Example to try on your own machine (not run here):*

```python
# Example only: needs SQLAlchemy, a PostgreSQL driver and a real database
# pip install sqlalchemy psycopg2-binary
from sqlalchemy import create_engine

engine = create_engine("postgresql://user:password@host:5432/beanthere")
df = pd.read_sql_query("SELECT * FROM sales LIMIT 10", engine)
```

## 6.7 Reading from URLs and web APIs

### Files on the web

Every pandas reader that takes a file path also accepts a **URL**. If a CSV is published on the web, you can read it directly without downloading it first. Here is an example to try on your own machine (it needs an internet connection). It loads the small "tips" dataset that the Seaborn project publishes on GitHub:

*Example to try on your own machine (not run here):*

```python
# Example to try on your own machine (needs internet access)
url = ("https://raw.githubusercontent.com/mwaskom/"
       "seaborn-data/master/tips.csv")
tips = pd.read_csv(url)
tips.head()
```

### Web APIs

Bean There's owner suspects Cold Brew sells better on warm days. The free Open-Meteo weather service returns daily temperatures without needing an account. Here is how you would request a week of forecasts for London. Again, this is an example to try on your own machine:

*Example to try on your own machine (not run here):*

```python
# Example to try on your own machine (needs internet access)
import requests

response = requests.get(
    "https://api.open-meteo.com/v1/forecast",
    params={
        "latitude": 51.51,
        "longitude": -0.13,
        "daily": "temperature_2m_max",
        "timezone": "Europe/London",
    },
    timeout=10,
)
response.raise_for_status()   # stop with an error if the request failed
data = response.json()        # the JSON body as Python dicts and lists
weather = pd.DataFrame(data["daily"])
weather.head()
```

The last two steps are exactly what you did with the loyalty file in Section 6.5. An API response is just JSON text that arrived over the network instead of from a file. You can prove that to yourself offline: read the loyalty file as **text**, then parse it with `json.loads()` (the "s" is for "string"), which is what `response.json()` does behind the scenes:

In [29]:
with open("../data/ch06_loyalty_members.json") as f:
    body = f.read()            # plain text, like an API response body

print(type(body), len(body), "characters")
payload = json.loads(body)     # text -> Python dicts and lists
pd.json_normalize(payload["members"])[["member_id", "name"]].head(3)

<class 'str'> 3155 characters

   member_id          name
0      50101      Ana Park
1      50102      Ben Lowe
2      50103  Chloe Moreau

## 6.8 Writing data out

### Building something worth saving

Let's make a small report comparing each store's monthly revenue with the finance targets we loaded from Excel. First, actual revenue per store and month, using the `groupby` pattern from Chapter 1:

In [30]:
sales = pd.read_csv("../data/bean_there_sales.csv", parse_dates=["date"])
sales["month"] = sales["date"].dt.strftime("%Y-%m")
actual = sales.groupby(["store", "month"])["revenue"].sum()
actual.head(3)

store     month
Downtown  2026-01    22625.6
          2026-02    21787.8
          2026-03    25791.9
Name: revenue, dtype: float64

`.dt.strftime("%Y-%m")` formats each date as text like `2026-01`, matching the `month` column in the targets sheet. The result has a two-level index of store and month. If we give `targets` the same index, pandas lines the two up **by label** when we combine them, just as Series did in Chapter 5:

In [31]:
report = targets.set_index(["store", "month"])
report["actual"] = actual.round(2)
report["vs_target_pct"] = (
    (report["actual"] / report["revenue_target"] - 1) * 100
).round(1)
report = report.reset_index()
report

        store    month  revenue_target    actual  vs_target_pct
0    Downtown  2026-01           22000  22625.60            2.8
1    Downtown  2026-02           21000  21787.80            3.8
2    Downtown  2026-03           24000  25791.90            7.5
3  University  2026-01           16500  15920.50           -3.5
4  University  2026-02           15500  16045.90            3.5
5  University  2026-03           18500  18604.00            0.6
6   Riverside  2026-01           13000  12865.10           -1.0
7   Riverside  2026-02           12500  12421.05           -0.6
8   Riverside  2026-03           14500  14852.05            2.4

### CSV

`.to_csv()` writes a DataFrame to a CSV file:

In [32]:
report.to_csv("../data/ch06_out_target_report.csv", index=False)

It is good practice to read a file back to check it:

In [33]:
pd.read_csv("../data/ch06_out_target_report.csv").head(3)

      store    month  revenue_target   actual  vs_target_pct
0  Downtown  2026-01           22000  22625.6            2.8
1  Downtown  2026-02           21000  21787.8            3.8
2  Downtown  2026-03           24000  25791.9            7.5

### Excel, with several sheets

To write one DataFrame to an Excel file, call `.to_excel("file.xlsx", index=False)`. To write **several** sheets into one workbook, use `pd.ExcelWriter` in a `with` block:

In [34]:
store_totals = (
    report.groupby("store")[["revenue_target", "actual"]].sum()
)

with pd.ExcelWriter("../data/ch06_out_target_report.xlsx") as writer:
    report.to_excel(writer, sheet_name="By month", index=False)
    store_totals.to_excel(writer, sheet_name="By store")

pd.ExcelFile("../data/ch06_out_target_report.xlsx").sheet_names

['By month', 'By store']

### JSON

For a web developer or another program, JSON is often the format they want. `orient="records"` produces a list of records, the same shape as the menu file, and `indent=2` makes it readable:

In [35]:
text = report.head(2).to_json(orient="records", indent=2)
print(text)

[
  {
    "store":"Downtown",
    "month":"2026-01",
    "revenue_target":22000,
    "actual":22625.6,
    "vs_target_pct":2.8
  },
  {
    "store":"Downtown",
    "month":"2026-02",
    "revenue_target":21000,
    "actual":21787.8,
    "vs_target_pct":3.8
  }
]

### SQL

`.to_sql()` writes a DataFrame into a database table. `if_exists="replace"` overwrites the table if it is already there; use `"append"` to add rows instead:

In [36]:
with sqlite3.connect("../data/ch06_out_reports.db") as out_con:
    report.to_sql("target_report", out_con,
                  if_exists="replace", index=False)
    check = pd.read_sql_query(
        "SELECT store, month, vs_target_pct FROM target_report "
        "WHERE vs_target_pct < 0",
        out_con,
    )
out_con.close()
check

        store    month  vs_target_pct
0  University  2026-01           -3.5
1   Riverside  2026-01           -1.0
2   Riverside  2026-02           -0.6

## 6.9 Working with large files

### How much memory does a DataFrame use?

We hide the `line_id` column when printing, purely to keep the table narrow enough for the page.

In [37]:
receipts = pd.read_csv("../data/ch06_bean_there_receipts.csv")
print(receipts.shape)
receipts.drop(columns="line_id").head(3)

(26696, 7)

          timestamp       store     product  quantity  unit_price      payment
0  2026-01-01 06:05    Downtown   Croissant         2        3.25          App
1  2026-01-01 06:13  University  Cappuccino         1        4.25  Contactless
2  2026-01-01 06:18    Downtown       Latte         2        4.50  Contactless

`.memory_usage(deep=True)` reports the bytes each column takes in memory. `deep=True` makes pandas measure text columns properly:

In [38]:
mem = receipts.memory_usage(deep=True)
print((mem / 1_000_000).round(2))
print(f"Total: {mem.sum() / 1_000_000:.1f} MB")

Index         0.00
line_id       0.21
timestamp     1.74
store         1.55
product       1.54
quantity      0.21
unit_price    0.21
payment       1.49
dtype: float64
Total: 7.0 MB

### Load fewer columns with `usecols`

The cheapest data is data you never load. If the question is "how many of each product did each store sell?", you only need three columns:

In [39]:
small = pd.read_csv(
    "../data/ch06_bean_there_receipts.csv",
    usecols=["store", "product", "quantity"],
)
print(f"{small.memory_usage(deep=True).sum() / 1_000_000:.1f} MB")

3.3 MB

### Smaller types with `dtype`

Next, tell pandas what type each column should be. Text columns with a few repeated values are perfect for the **category** dtype, which stores each distinct value once and replaces every row's text with a small number pointing to it. Small whole numbers fit in `int8` (−128 to 127) instead of the default 64-bit `int64`:

In [40]:
small = pd.read_csv(
    "../data/ch06_bean_there_receipts.csv",
    usecols=["store", "product", "quantity"],
    dtype={"store": "category", "product": "category",
           "quantity": "int8"},
)
print(small.dtypes)
print(f"{small.memory_usage(deep=True).sum() / 1_000_000:.2f} MB")

store       category
product     category
quantity        int8
dtype: object
0.08 MB

Choosing the columns and their types cut memory by more than 95%, and the data is just as easy to work with. Group by the category columns as usual (`observed=True` tells pandas to list only combinations that actually appear in the data):

In [41]:
units = (
    small.groupby(["store", "product"], observed=True)["quantity"]
    .sum()
)
units.head(6)

store     product
Downtown  Blueberry Muffin    2149
          Cappuccino          3175
          Cold Brew           2624
          Croissant           2814
          Espresso            2578
          Latte               4673
Name: quantity, dtype: int64

### Reading in chunks with `chunksize`

Sometimes even the columns you need will not fit in memory. Then you can read the file in **chunks**: pieces of a fixed number of rows, processed one at a time. Passing `chunksize` makes `read_csv` return a reader you loop over, rather than one big DataFrame. The trick is to summarize each chunk and keep only the small summaries:

In [42]:
reader = pd.read_csv(
    "../data/ch06_bean_there_receipts.csv",
    usecols=["store", "payment", "quantity", "unit_price"],
    chunksize=10_000,
)

pieces = []
for chunk in reader:
    chunk["amount"] = chunk["quantity"] * chunk["unit_price"]
    pieces.append(chunk.groupby(["store", "payment"])["amount"].sum())
    print("chunk of", len(chunk), "rows")

chunk of 10000 rows
chunk of 10000 rows
chunk of 6696 rows

Each chunk is an ordinary DataFrame, so everything from Chapter 5 works inside the loop. We now have three small summaries, one per chunk. Stack them with `pd.concat()` and add them up once more to get the final answer:

In [43]:
by_payment = pd.concat(pieces).groupby(level=["store", "payment"]).sum()
by_payment.unstack().round(2)

payment          App     Card     Cash  Contactless
store
Downtown    10526.45  24307.1  6992.75     28379.00
Riverside    6017.30  14154.2  4003.55     15963.15
University   7502.70  17841.9  4997.30     20228.50

`groupby(level=...)` groups by the index levels instead of by columns, and `.unstack()` turns the payment level into columns so the table is easier to read (Chapter 8 explains both). Only 10,000 rows were ever in memory at once, yet the totals cover the whole quarter. The overall total matches the daily sales file:

In [44]:
print(f"${by_payment.sum():,.2f}")

$160,913.90

## 6.11 Exercises

Open `ch06_data_in_out.ipynb` and add your answers at the bottom. Solutions are in Appendix D.

1. Read only the first 10 rows of `bean_there_sales.csv`, keeping just the `date`, `product` and `quantity` columns. *Hint:* `nrows` and `usecols`.
2. Load `ch06_supplier_invoices.csv` correctly in a single `read_csv` call, and find which supplier's invoices had the largest **average** total. Then check: what happens to the `Preis` column if you leave out `decimal=","`?
3. Load the `Targets` sheet of `ch06_store_targets.xlsx` using `header=3` instead of `skiprows=3`. Do you get the same table? Then load only the first two columns with `usecols="A:B"`.
4. From `ch06_loyalty_members.json`, build a DataFrame with one row per visit and find each **home store's** total visit spend. Did any member visit a store other than their home store? *Hint:* compare the `store` and `home_store` columns.
5. Write a SQL query against `ch06_bean_there.db` that returns the total quantity of each product at Riverside, sorted from highest to lowest. *Hint:* `WHERE`, `GROUP BY`, `ORDER BY ... DESC`.
6. Using `params`, write a small function `product_sales(con, product)` that returns the daily rows for any product. Call it for "Croissant" and report the number of rows and the total revenue.
7. Save the `invoices` DataFrame from Section 6.3 to a UTF-8 CSV with standard commas and decimal points, read it back, and confirm the totals per supplier are unchanged. Name the file `../data/ch06_out_invoices.csv`.
8. Using `chunksize=5_000` on `ch06_bean_there_receipts.csv`, count how many receipt lines each **hour of the day** has across the quarter. Which hour is busiest? *Hint:* in each chunk, `pd.to_datetime(chunk["timestamp"]).dt.hour` gives the hour; count with `.value_counts()` and combine the counts at the end.